# .goreleaser.yaml for WPOD/WordPress in Docker
# Builds and releases 'wpod' (main CLI) and 'manage' (instance tool) for multiple platforms

project_name: wpod

dist: dist

dockers: []

builds:
  - id: wpod
    main: ./cmd/wp-manager
    binary: wpod
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    # Output: dist/wpod-{{ .Os }}-{{ .Arch }}{{ if eq .Os "windows" }}.exe{{ end }}
    # Custom output name for each platform
    hooks:
      post: |
        echo "Built wpod for $GOOS-$GOARCH"

  - id: manage
    main: ./cmd/manage
    binary: manage
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    hooks:
      post: |
        echo "Built manage for $GOOS-$GOARCH"
archives:
  - id: wpod-archive
    builds: [wpod, manage]
    format: tar.gz
    name_template: "wpod-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - dist/wp* # include all wpod binaries
      - dist/manage* # include all manage binaries
      - setup*
      - Taskfile.yml

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: ${{ github.repository_owner }}
    name: ${{ github.event.repository.name }}

signs: []

# Optionally, add brew, scoop, or docker sections if needed
